# vim: set ft=ansible et ts=2 sw=2:
---
# Tasks for compiling Modsecurity3 and installing OWASP CRS v3

- name: Get Nginx modules location
  shell: nginx -V 2>&1 | grep "configure arguments:" | sed -e 's/.*--modules-path=\([^ ]*\).*/\1/'
  register: _nginx_modules_location
  changed_when: false
  when: nginx_modules_location is not defined

- name: Set variable nginx_modules_location
  set_fact:
    nginx_modules_location: "{{ _nginx_modules_location.stdout }}"
  when: nginx_modules_location is not defined

- name: Clear previous compilation
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/ModSecurity"
    - "~/ModSecurity-nginx"
    - "~/Nginx"
    - "/tmp/nginx-*.tar.gz"
    - "{{ nginx_modules_location }}/ngx_http_modsecurity_module.so"
    - "{{ nginx_conf_dir }}/modsec/"
  when: nginx_modsec3_crs3_force_compile

- name: Obtain Modsecurity source code for branch v3/master
  git:
    repo: "https://github.com/SpiderLabs/ModSecurity"
    dest: "~/ModSecurity"
    depth: 1
    version: "v3/master"
    force: yes

- name: Init submodules, configure, build, make install
  command: "{{ item }}"
  args:
    chdir: "~/ModSecurity"
    creates: "/usr/local/modsecurity/lib/libmodsecurity.so"
  with_items:
    - "git submodule init"
    - "git submodule update"
    - "./build.sh"
    - "./configure"
    - "make"
    - "make install"
  when: not modsec3_present or nginx_modsec3_crs3_force_compile

- name: Obtain Modsecurity-nginx source code
  git:
    repo: "https://github.com/SpiderLabs/ModSecurity-nginx"
    dest: "~/ModSecurity-nginx"
    depth: 1
    force: yes
  when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

- name: Download Nginx source code
  get_url:
    url: "https://nginx.org/download/nginx-{{ nginx_modsec3_crs3_nginx_version }}.tar.gz"
    dest: "/tmp/nginx-{{ nginx_modsec3_crs3_nginx_version }}.tar.gz"
  when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

- name: Create folder for Nginx source code
  file:
    path: "~/Nginx"
    state: directory
  when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

- name: Extract Nginx source code
  unarchive:
    src: "/tmp/nginx-{{ nginx_modsec3_crs3_nginx_version }}.tar.gz"
    dest: "~/Nginx"
    remote_src: yes
  when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

- name: Configure and make ModSecurity3 for Nginx module
  shell: "{{ item }}"
  args:
    chdir: "~/Nginx/nginx-{{ nginx_modsec3_crs3_nginx_version }}"
    creates: "~/mods.so"
  with_items:
    - "CFLAGS=-Wno-error ./configure --with-compat --add-dynamic-module=../../ModSecurity-nginx"
    - "make modules"
  when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

# - name: import nginx role Debian/Ubuntu vars
#   include_vars:
#     file: "../jdauphant.nginx/vars/Debian.yml"
#   when:
#     - ansible_os_family == "Debian"
#     #- nginx_python_selinux_pkgs is not defined

# - name: import nginx role Redhat/Centos vars
#   include_vars:
#     file: "../jdauphant.nginx/vars/Redhat.yml"
#   when:
#     - ansible_os_family == "Redhat"
#     #- nginx_python_selinux_pkgs is not defined

- name: Copy Modsecurity-nginx module to Nginx modules folder
  copy:
    src: "~/Nginx/nginx-{{ nginx_modsec3_crs3_nginx_version }}/objs/ngx_http_modsecurity_module.so"
    dest: "{{ nginx_modules_location }}/ngx_http_modsecurity_module.so"
    remote_src: yes
  when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

# - name: Enable module in Nginx
#   template:
#     src: 50-mod-http-modsecurity.conf.j2
#     dest:  "{{ nginx_conf_dir }}/conf.d/50-mod-http-modsecurity.conf"   
#   when: not modsec3_nginx_present or nginx_modsec3_crs3_force_compile

- name: Create folder for Modsec config and rules
  file:
    #path: /etc/nginx/modsec
    path: "{{ nginx_conf_dir }}/modsec"
    state: directory
  when: not crs3_present or nginx_modsec3_crs3_force_compile

- name: Copy recommended conf to become modsecurity.conf
  copy:
    src: "~/ModSecurity/modsecurity.conf-recommended"
    dest: "{{ nginx_conf_dir }}/modsec/modsecurity.conf"
    remote_src: yes
  when: not crs3_present or nginx_modsec3_crs3_force_compile

- name: Copy unicode.mapping file also
  copy:
    src: "~/ModSecurity/unicode.mapping"
    dest: "{{ nginx_conf_dir }}/modsec/unicode.mapping"
    remote_src: yes
  when: not crs3_present or nginx_modsec3_crs3_force_compile

- name: Activate blocking rather than detection only
  replace:
    path: "{{ nginx_conf_dir }}/modsec/modsecurity.conf"
    regexp: "SecRuleEngine DetectionOnly"
    replace: "SecRuleEngine On"
  when: nginx_modsec3_crs3_block_mode == true and (not crs3_present or nginx_modsec3_crs3_force_compile)


- name: Create a main.conf from template
  template:
    src: main.conf.j2
    dest: "{{ nginx_conf_dir }}/modsec/main.conf"
  when: not crs3_present or nginx_modsec3_crs3_force_compile

- name: Obtain OWASP Modsecurity Rules
  git:
    repo: "https://github.com/coreruleset/coreruleset"
    dest: "{{ nginx_conf_dir }}/modsec/owasp-modsecurity-crs"
    version: "{{ nginx_modsec3_crs_version }}"
    depth: 1
  when: not crs3_present or nginx_modsec3_crs3_force_compile

- name: Copy crs-setup.conf.example to become crs-setup.conf
  copy:
    src: "{{ nginx_conf_dir }}/modsec/owasp-modsecurity-crs/crs-setup.conf.example"
    dest: "{{ nginx_conf_dir }}/modsec/owasp-modsecurity-crs/crs-setup.conf"
    remote_src: yes
  when: not crs3_present or nginx_modsec3_crs3_force_compile
